### ISSUE TITLE
Utility to join components (OS-aware)

### ISSUE THREAD

**Issue by mizlan** [Raynes/fs#119]
Is there a way to join components of a path, for example something like this?

```clj
(fs/join "/Users" "michael" "code")
;; => "/Users/michael/code"
```

It would be similar to Python's [`os.path.join`](https://docs.python.org/3/library/os.path.html#os.path.join) for reference.

Since most of the functions in this library return Files, i'm not sure how this should work for a non-existent filepath.

**Comment by SalvatoreTosti** [comment]
@mizlan I think you can achieve this using the `Java File.separator` via interop. :)
`(clojure.string/join (. java.io.File separator) ["Users" "michael" "code"])`

**Comment by mizlan** [comment]
This works great, thank you so much!
